# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest

    restart: always
  test-db:
    image: postgres
    ports:
      - 5434:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest

    restart: always